<?php

/**
 * @file
 * Primary module hooks for Colour Picker Fields module.
 */

/**
 * Implements hook_theme().
 */
function localgov_microsites_colour_picker_fields_theme($existing, $type, $theme, $path) {
  return array(
    'colour_picker_fields' => array(
      'render element' => 'input',
      'template' => 'color-picker-input',
    ),
  );
}
/**
 * Implements hook_form_FORM_ID_alter().
 */
function localgov_microsites_colour_picker_fields_form_group_microsite_edit_form_alter(&$form, $form_state, $form_id) {
  $form['#attached']['library'][] =  'localgov_microsites_colour_picker_fields/localgov_microsites_colour_picker_fields';
  $fields = [
    'lgms_primary_colour',
    'lgms_secondary_colour',
    'lgms_footer_background_colour',
    'lgms_footer_background_colour',
    'lgms_footer_link_colour',
    'lgms_footer_link_hover_colour',
    'lgms_footer_text_colour',
    'lgms_header_bg_colour',
    'lgms_header_link_colour',
    'lgms_header_link_hover_colour',
    'lgms_header_text_colour',
    'lgms_heading_1_font_colour',
    'lgms_heading_2_font_colour',
    'lgms_heading_3_font_colour',
    'lgms_heading_4_font_colour',
    'lgms_heading_5_font_colour',
    'lgms_heading_6_font_colour',
    'lgms_pre_header_bg_colour',
    'lgms_pre_header_link_colour',
    'lgms_pre_header_link_hover',
    'lgms_pre_header_text_colour',
    'lgms_primary_colour',
    'lgms_secondary_colour',
    'lgms_text_colour_dark',
    'lgms_text_colour_light',
  ];

  foreach ($fields as $field) {
    $form[$field]['widget'][0]['value']['#theme'] = 'colour_picker_fields';
    $form[$field]['widget'][0]['value']['#attributes']['class'][] = 'form-element';
  }
}